online_portfolio/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from .forms import LoginForm, CustomPassReset, CustomPassResetConf

app_name = "accounts"

urlpatterns = [
    path("signup/", views.EnterEmail.as_view(), name="enter_email"),
    path("signup/<str:encoded_email>/", views.SignupView.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(
            template_name="accounts/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="accounts/password_reset_sub.txt",
            success_url="/accounts/password_reset_done/",
            form_class=CustomPassReset,
        ),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        views.CustomPasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<str:uidb64>/<str:token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            form_class=CustomPassResetConf,
            success_url="/accounts/password_reset_complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        views.CustomPassResetComp.as_view(),
        name="password_reset_complete",
    ),
]

online_portfolio/online_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("portfolio/", include("portfolio.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("about/", views.About.as_view(), name="about"),
]

online_portfolio/accounts/models.py
from django.db import models

# Create your models here.
"""
The default django user model is used.
https://docs.djangoproject.com/en/3.0/ref/contrib/auth/
"""

online_portfolio/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordResetForm
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    SetPasswordForm,
)


def _existing_email(email):
    """
    It is a validator which checks if the any user with the given email exists in the system.
    :param email: email to check
    :type: str
    :rtype: bool
    """
    try:
        User.objects.get(email=email)
    except User.DoesNotExist:
        return False

    return True


def existing_email(should_exist=False):
    """
    It is a validator which checks if the any user with the given email exists in the system.
    :param email: email to check
    :param should_exist: the desired result, regarding email existence
    :type: str
    :rtype: bool
    """

    def validator(email):
        result = _existing_email(email)

        if result != should_exist:
            if not should_exist:
                raise forms.ValidationError(
                    "User with this email already exists. Please login."
                )

            raise forms.ValidationError(
                mark_safe(
                    "User with this email does not exists. Please <a href='/accounts/signup/'>signup</a>."
                )
            )

        return

    return validator


class EnterEmailForm(forms.Form):
    user_email = forms.EmailField(
        label="Enter Email Here",
        max_length=100,
        validators=[existing_email],
        widget=forms.EmailInput(
            attrs={"placeholder": "Enter Your Email", "class": "form-control"}
        ),
    )


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        validators=[existing_email()],
        widget=forms.EmailInput(
            attrs={"readonly": True, "id": "email", "class": "form-control"}
        ),
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        widgets = {
            "username": forms.TextInput(
                attrs={"id": "username", "class": "form-control"}
            ),
            "password1": forms.TextInput(
                attrs={"id": "password1", "class": "form-control"}
            ),
            "password2": forms.TextInput(
                attrs={"id": "password2", "class": "form-control"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password1"].widget.attrs["id"] = "password1"
        self.fields["password2"].widget.attrs["class"] = "form-control"
        self.fields["password2"].widget.attrs["id"] = "password2"


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", "id": "username"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control", "id": "password"}),
        help_text=mark_safe(
            'Forgot Password? Click <a href="/accounts/password_reset/">here</a>.'
        ),
    )

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)


class CustomPassReset(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"id": "emailInput", "class": "form-control"}),
        validators=[existing_email(should_exist=True)],
    )

    def __init__(self, *args, **kwargs):
        super(CustomPassReset, self).__init__(*args, **kwargs)


class CustomPassResetConf(SetPasswordForm):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"id": "password1", "class": "form-control"})
    )

    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"id": "password2", "class": "form-control"})
    )

    def __init__(self, *args, **kwargs):
        super(CustomPassResetConf, self).__init__(*args, **kwargs)

online_portfolio/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
import threading
from .forms import EnterEmailForm, SignUpForm, CustomPassReset
from helper import *
from portfolio.helper import create_default_project
from decouple import config
from datetime import datetime
from django.contrib import messages
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login


class EnterEmail(View):
    """
    This view accepts email from new user and sends him the signup link.
    """

    template = "accounts/enter_email.html"
    email = "accounts/signup_email.html"

    def get(self, request):
        form = EnterEmailForm()
        return render(
            request=request, template_name=self.template, context={"form": form}
        )

    def post(self, request):
        form = EnterEmailForm(request.POST)

        # if form is invalid, show errors to user
        if not form.is_valid():
            return render(
                request=request, template_name=self.template, context={"form": form}
            )

        # prepare the encrypted signup link
        user_email = form.cleaned_data["user_email"]
        encoded_email = encode_data(config("NEW_EMAIL_HASH"), user_email)
        signup_link = (
            request.scheme
            + "://"
            + request.get_host()
            + "/accounts/signup/"
            + encoded_email
            + "/"
        )

        # send encrypted signup link to user
        email_content = render_to_string(
            template_name=self.email, context={"signup_link": signup_link}
        )
        email_subject = "<Port>folio Signup Link"

        mail = threading.Thread(
            target=send_mail, args=(user_email, email_content, email_subject)
        )
        mail.start()
        # return to the same page
        messages.success(request, "Please check your email")
        return redirect("accounts:enter_email")


class SignupView(View):
    template = "accounts/signup.html"

    def get(self, request, encoded_email):
        # decode the email
        user_email = decode_data(config("NEW_EMAIL_HASH"), encoded_email)

        """
        if user has already signed up, form submission will give error
        therefore no need to check here.
        """

        # create signup form for the email
        form = SignUpForm(initial={"email": user_email})

        # render the form
        return render(request, template_name=self.template, context={"form": form})

    def post(self, request, encoded_email):
        form = SignUpForm(request.POST)

        # if form is invalid, show errors to user
        if not form.is_valid():
            return render(request, template_name=self.template, context={"form": form})

        """
        check email field for any tampering by the user, by comparing to encoded_email.
        """
        decoded_email = decode_data(config("NEW_EMAIL_HASH"), encoded_email)

        # warn user about the tampering
        if decoded_email != form.cleaned_data["email"]:
            messages.error(request, "Don't act over-smart!!")
            return render(request, template_name=self.template, context={"form": form})

        # in case of no tampering, register as new user.
        form.save()

        # login the new user
        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
        )

        create_default_project(user)

        login(request=request, user=user)

        return redirect("home")


class CustomPasswordResetDone(View):
    @staticmethod
    def get(request):
        messages.success(request, "Check your mail!")
        return redirect(to="accounts:password_reset")


class CustomPassResetComp(View):
    @staticmethod
    def get(request):
        messages.success(request, "Password Changed Successfully")
        return redirect(to="accounts:login")

online_portfolio/templates/accounts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'accounts/css/accounts.css' %}">
    <link rel="stylesheet" href="{% static 'generic/css/alerts.css' %}">
    
    <title>{% block title %}{% endblock %}</title>
</head>

<body style="text-align:center; width:100%; min-height: 100vh; position: relative;">
    {% block content %}
    {% endblock %}
</body>

<script type="text/javascript" src="{% static 'generic/js/alerts.js' %}"></script>
{% block scripts %}
{% endblock scripts %}
</html>

online_portfolio/templates/accounts/enter_email.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}
Sign Up
{% endblock %}

{% block content %}
{% include 'render_messages.html' %}
    <div class="container" id="enterEmailContent" style="display:inline-block;">
        <div id="enterEmailImage" class="container col-sm-4 float-right">
            <img onclick="githubLogin();" src="{% static 'portfolio/github.png' %}" class="img-fluid" style="width: 100px;">
            <a id="githubLogin" style="display: none;" href="{% url 'social:begin' 'github' %}"></a>
        </div>
        
        <div class="container col-sm-8 float-left" id="enterEmailForm">
            <form method="post" action="{% url 'accounts:enter_email' %}">
            {% csrf_token %}
            
            {% if form.user_email.errors %}
            <div class="container text-danger" style="margin-bottom: 15px;">
                {% for error in form.user_email.errors %}
                <small>{{error}}</small>
                {% endfor %}
            </div>
            {% endif %}
            
            <div class="form-group">
                {{form.user_email}}
            </div>

            <button type="submit" class="btn btn-primary">Send Invite Link</button>
        </form>
        <br>

        <p class="text-muted" id="enterEmailText">Already have an account? Login <a href="{% url 'accounts:login' %}">here</a>.</p>
        </div>
        
    </div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'accounts/js/enter_email.js' %}"></script>
{% endblock scripts %}

online_portfolio/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}
Login
{% endblock %}

{% block content %}
{% include 'render_messages.html' %}
    <div id="loginContent" class="container">
        <div id="loginImage" class="container float-right">
            <img style="max-width: 100px;" onclick="githubLogin();" src="{% static 'portfolio/github.png' %}" class="img-fluid">
            <a id="githubLogin" style="display: none;" href="{% url 'social:begin' 'github' %}"></a>
        </div>
        
        <div class="container float-left" id="loginForm">
        <form method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="username">Username</label>
                {{form.username}}
                
                {% for error in form.username.errors %}
                <small class="text-danger">{{error}}</small>
                {% endfor %}
                
                <small class="text-muted">{{form.username.help_text}}</small>
            </div>
            
            <div class="form-group">
                <label for="password">Password</label>
                {{form.password}}
                
                {% for error in form.password.errors %}
                <small class="text-danger">{{error}}</small>
                {% endfor %}
                
                <small class="text-muted">{{form.password.help_text}}</small>
            </div>
            
            <div style="margin-bottom: 15px;">
            {% for error in form.non_field_errors %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
            </div>
            
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <hr>
        <p class="text-muted">Do not have account? Signup <a href="{% url 'accounts:enter_email' %}">here</a>.</p>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'accounts/js/enter_email.js' %}"></script>
{% endblock scripts %}

online_portfolio/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}

{% block title %}
Reset Password
{% endblock %}

{% block content %}

{% include 'render_messages.html' %}

<div id="PassResetConfForm" class="container">
    <form method="post" action="#">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="password1">New Password:</label>
            {{form.new_password1}}
        </div>
        
        <div class="container" style="margin-bottom: 15px;">
            {% for error in form.new_password1.errors %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
        </div>
        
        <div class="form-group">
            <label for="password2">Confirm Password:</label>
            {{form.new_password2}}
        </div>
        
        <div class="container" style="margin-bottom: 15px;">
            {% for error in form.new_password2.errors %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
        </div>

        <button type="submit" class="btn btn-primary">Change Password</button>
    </form>
</div>
{% endblock %}

online_portfolio/templates/accounts/password_reset_email.html
Hello {{user.username}},

Follow the following link to reset your password:

{{ protocol}}://{{ domain }}{% url "accounts:password_reset_confirm" uidb64=uid token=token %}

Thank you for using <Port>folio,
Manthan Chauhan

online_portfolio/templates/accounts/password_reset_form.html
{% extends 'accounts/base.html' %}

{% block title %}
Reset Password
{% endblock %}

{% block content %}
{% include 'render_messages.html' %}

<div id="passResetContent" class="container">
    <form method="post" action="#">
        {% csrf_token %}
        
        <div class="container">
            {% for error in form.email.errors %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
        </div>
        
        <br>
        
        <div class="form-group" style="text-align: left;">
            <label for="emailInput">Registered Email:</label>
            {{form.email}}
        </div>
        
        <button type="submit" class="btn btn-primary">Send Reset Link</button>
    </form>
</div>
{% endblock %}

online_portfolio/templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block title %}
Create Account
{% endblock %}

{% block content %}
<div style="display:inline-block; margin-top:10vh;">
    <form method="post" action="" style="text-align:left;margin:15px;">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="email">Email address:</label>
            {{form.email}}
            
            <ul>
                {% for error in form.email.errors %}
                <li><small class="text-danger">{{error}}</small></li>
                {% endfor %}
            </ul>
        </div>
        
        <div class="form-group">
            <label for="username">Username:</label>
            {{form.username}}
        
            <ul>
                {% for error in form.username.errors %}
                <li><small class="text-danger">{{error}}</small></li>
                {% endfor %}
            </ul>
            
        </div>
        
        <div class="row">
            <div class="form-group col-6">
                <label for="password1">Password:</label>
                {{form.password1}}
            </div>
            
            <div class="form-group col-6">
                <label for="password2">Confirm Password:</label>
                {{form.password2}}
            </div>
        </div>
        
        <ul>
            {% for error in form.password2.errors %}
            <li><small class="text-danger">{{error}}</small></li>
            {% endfor %}
            {% for error in form.password1.errors %}
            <li><small class="text-danger">{{error}}</small></li>
            {% endfor %}
        </ul>
        
        <small class="text-muted">{{form.password1.help_text}}</small>
        
        <button type="submit" class="btn btn-primary">Create Account</button>
    </form>

    <hr>
    <p class="text-muted">Already have an account? Login <a href="{% url 'accounts:login' %}">here</a>.</p>
</div>
{% endblock %}

online_portfolio/templates/accounts/signup_email.html
Hi,<br>
Your signup link is:<br>
<br>
{{signup_link}}<br>
<br>
Thank you for choosing us.<br>
Team &lt;Port&gt;folio.<br>