online_portfolio/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from .forms import LoginForm, CustomPassReset, CustomPassResetConf

app_name = "accounts"

urlpatterns = [
    path("signup/", views.EnterEmail.as_view(), name="enter_email"),
    path("signup/<str:encoded_email>/", views.SignupView.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(
            template_name="accounts/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="accounts/password_reset_sub.txt",
            success_url="/accounts/password_reset_done/",
            form_class=CustomPassReset,
        ),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        views.CustomPasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<str:uidb64>/<str:token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            form_class=CustomPassResetConf,
            success_url="/accounts/password_reset_complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        views.CustomPassResetComp.as_view(),
        name="password_reset_complete",
    ),
]

online_portfolio/online_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("portfolio/", include("portfolio.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("about/", views.About.as_view(), name="about"),
]

online_portfolio/portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path("edit/", views.PortfolioEdit.as_view(), name="portfolio_edit"),
    path("update_about/", views.UpdateAboutSection.as_view(), name="update_about"),
    path("edit_projects/", views.EditProjects.as_view(), name="edit_projects"),
    path("delete_project/", views.DeleteProject.as_view(), name="delete_project"),
    path("add_project/", views.AddNewProject.as_view(), name="add_project"),
    path("export_portfolio/", views.ExportPortfolio.as_view(), name="export_portfolio"),
    path("add_new_skill/", views.AddSkill.as_view(), name="add_new_skill"),
    path("delete_skill/", views.DeleteSkill.as_view(), name="delete_skill"),
    path("edit_category_name/", views.change_category_name, name="edit_category_name"),
]

online_portfolio/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Me</title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&family=Playfair+Display:ital@1&display=swap" rel="stylesheet">    <link rel="stylesheet" href="{% static 'generic/css/about.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>
<body style="background: #e6f7ff;">

{% include 'navbar.html' %}

<div style="text-align: center; margin-top: 15px;">
    <div id="aboutContent">
        <h1 id="aboutHeading"><strong>About Me</strong></h1>
        <p>My name is Manthan Chauhan, I'm a Web Developer and Competitive Programmer, and an occasional Technical Content Writer on Geeksforgeeks & Medium. At the moment, I'm a B.tech undergrad in Electronics & Communication at Indraprastha University, Delhi, and will be graduating this year (2020).</p>
        <p id="aboutPara2">I started my programming journey with Competitive Programming at Codechef.com, with C & C++. After that, I started developing small to medium level projects using Python. Primarily I'm a Backend Developer in Django, but I also have some experience in Frontend Development and DevOps.</p>
        <p>This <a href="{% url 'accounts:login' %}" class="aboutLinks">Online Portfolio Maker</a> is my biggest solo project by now, which has encouraged me to expand my skill set into various domains. The project is <strong>under development</strong> & is expected to be complete by this year.</p>
        <hr>
        <p class="sectionHeadings"><strong>Lets connect to exchange thoughts</strong></p>

        <div id="aboutSocial" class="card">
            <div class="card-body socialBody">
                <a href="https://www.linkedin.com/in/manthan-chauhan-83b1b4140/" target="_blank"><img class="socialIcons" src="{% static 'portfolio/linkedin.png' %}"></a>
                <a href="https://github.com/manthanchauhan" target="_blank"><img class="socialIcons img-fluid" src="{% static 'portfolio/github.png' %}"></a>
                <a href="mailto:manthanchauhan913@gmail.com"><img class="socialIcons img-fluid" src="{% static 'portfolio/gmail.png' %}"></a>
                <a href="https://medium.com/@manthanchauhan913" target="_blank"><img class="socialIcons img-fluid" src="{% static 'generic/medium.png' %}"></a>
                <a href="https://www.codechef.com/users/manthanchauhan" target="_blank"><img id="socialCodechef" class="socialIcons img-fluid" src="{% static 'portfolio/codechef.svg' %}"></a>
            </div>
        </div>
        
        <hr>
        <p class="sectionHeadings"><strong>Support the project</strong></p>
        <p>If you like this Online Portfolio Maker, I'd appreciate you to help me sustain it online. You can contact me via LinkedIn or Mail since currently I don't have any merchant accounts.
        <br><br><strong>Thank you!</strong></p>

        <br>
    </div>
</div>

{% include 'footer.html' %}
</body>
</html>

online_portfolio/templates/footer.html
<footer class="page-footer font-small bg-dark">
    <div class="footer-copyright text-center py-3" style="color:white;">© 2020 Copyright:
        {% if copyright_link and copyright_value %}
        <a href="{{copyright_link}}" target="_blank" style="color: white;">{{copyright_value}}</a>
        {% else %}
        <a href="{{request.scheme}}://{{request.META.HTTP_HOST}}" target="_blank" style="color:white;"> {{request.META.HTTP_HOST}}</a>
        {% endif %}
    </div>
</footer>

online_portfolio/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}"><strong>Portfolio</strong></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item {% if request.path == '/portfolio/edit/' %} active {% endif %}">
                <a class="nav-link" href="{% url 'portfolio:portfolio_edit' %}">Edit Portfolio</a>
            </li>
            
            {% if request.user.basicinfo.portfolio %}
            <li class="nav-item">
                <a class="nav-link" id="portLink2" href="{{request.user.basicinfo.portfolio}}" target="_blank">View Portfolio</a>
            </li>
            {% endif %}
            
            {% endif %}
            
            <li class="nav-item">
                <a class="nav-link {% if request.path == '/about/' %} active {% endif %}" href="{% url 'about' %}">About Me</a>
            </li>
            
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#">Feedback</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
            </li>
            {% endif %}
            
            {% if not request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:enter_email' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

online_portfolio/templates/render_messages.html
{% if messages %}
<div class="container alerts col-lg-4 col-md-8">
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success .alert-dismissable" role="alert">
              {{message}}
                
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger .alert-dismissable" role="alert">
              {{message}}
                
                <button aria-label="Close" class="close" data-dismiss="alert" type="button">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endif %}