online_portfolio/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from .forms import LoginForm, CustomPassReset, CustomPassResetConf

app_name = "accounts"

urlpatterns = [
    path("signup/", views.EnterEmail.as_view(), name="enter_email"),
    path("signup/<str:encoded_email>/", views.SignupView.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(
            template_name="accounts/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="accounts/password_reset_sub.txt",
            success_url="/accounts/password_reset_done/",
            form_class=CustomPassReset,
        ),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        views.CustomPasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<str:uidb64>/<str:token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            form_class=CustomPassResetConf,
            success_url="/accounts/password_reset_complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        views.CustomPassResetComp.as_view(),
        name="password_reset_complete",
    ),
]

online_portfolio/online_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("portfolio/", include("portfolio.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("about/", views.About.as_view(), name="about"),
]

online_portfolio/portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path("edit/", views.PortfolioEdit.as_view(), name="portfolio_edit"),
    path("update_about/", views.UpdateAboutSection.as_view(), name="update_about"),
    path("edit_projects/", views.EditProjects.as_view(), name="edit_projects"),
    path("delete_project/", views.DeleteProject.as_view(), name="delete_project"),
    path("add_project/", views.AddNewProject.as_view(), name="add_project"),
    path("export_portfolio/", views.ExportPortfolio.as_view(), name="export_portfolio"),
    path("add_new_skill/", views.AddSkill.as_view(), name="add_new_skill"),
    path("delete_skill/", views.DeleteSkill.as_view(), name="delete_skill"),
    path("edit_category_name/", views.change_category_name, name="edit_category_name"),
]

online_portfolio/portfolio/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.validators import MinValueValidator
from phonenumber_field.modelfields import PhoneNumberField
from .validators import all_space_validator
from django.conf import settings

# Create your models here.
class BasicInfo(models.Model):
    total_projects = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE, editable=False)
    name = models.CharField(
        default=settings.DEFAULT_BASIC_INFO["name"],
        max_length=40,
        validators=[all_space_validator],
    )
    email = models.EmailField(primary_key=True, max_length=50)
    phone1 = PhoneNumberField(null=True, blank=True)
    phone2 = PhoneNumberField(null=True, blank=True)
    about = models.CharField(
        default=settings.DEFAULT_BASIC_INFO["about"],
        max_length=2000,
        validators=[all_space_validator],
    )
    tag_line = models.CharField(
        default=settings.DEFAULT_BASIC_INFO["tag_line"], blank=True, max_length=55
    )
    call_of_contact = models.CharField(null=True, blank=True, max_length=400)
    profile_pic = models.CharField(
        max_length=200, default=settings.DEFAULT_BASIC_INFO["profile_pic"],
    )
    portfolio = models.CharField(null=True, blank=False, max_length=200)

    def update(self, data):
        self.__dict__.update(data)

    @staticmethod
    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
        """
        https://docs.djangoproject.com/en/3.0/ref/signals/#post-save
        :return: None
        """
        if created:
            BasicInfo.objects.create(user=instance, email=instance.email)


class Project(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)
    user_profile = models.ForeignKey(
        BasicInfo, on_delete=models.CASCADE, editable=False
    )
    title = models.CharField(default=settings.DEFAULT_PROJECT["title"], max_length=50)
    description = models.CharField(
        default=settings.DEFAULT_PROJECT["description"], max_length=500
    )
    skills = models.CharField(
        default=settings.DEFAULT_PROJECT["skills"], max_length=100
    )
    live_link = models.CharField(blank=True, null=True, max_length=100)
    code_link = models.CharField(blank=True, null=True, max_length=100)
    image = models.CharField(max_length=200, default=settings.DEFAULT_PROJECT["image"],)

    class Meta:
        unique_together = (("user_profile", "title"), ("user_profile", "timestamp"))

    def update(self, data):
        self.__dict__.update(data)

    def to_dict(self):
        ans = {
            "serial_no": self.pk,
            "title": self.title,
            "timestamp": self.timestamp,
            "description": self.description,
            "skills": self.skills,
            "live_link": self.live_link,
            "code_link": self.code_link,
            "image": self.image,
        }
        return ans


class Skill(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True, editable=False)
    user_profile = models.ForeignKey(
        to=BasicInfo, on_delete=models.CASCADE, editable=True,
    )
    skill_name = models.CharField(max_length=25)
    category = models.CharField(max_length=50)

    class Meta:
        unique_together = [("user_profile", "skill_name")]

online_portfolio/portfolio/forms.py
"""
forms for portfolio app
"""
from .models import BasicInfo, Project, Skill
from django.forms import ModelForm


class BasicInfoForm(ModelForm):
    class Meta:
        model = BasicInfo
        fields = ["name", "about", "tag_line", "profile_pic"]


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = "__all__"


class AddSkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = ["skill_name", "category", "user_profile"]

online_portfolio/portfolio/views.py
from django.shortcuts import render
from django.views import View
import datetime
import json
from pytz import UTC
from django.template.loader import render_to_string
from django.views.decorators.http import require_POST
from online_portfolio.classes import MediaStorage
from django.core.exceptions import ObjectDoesNotExist

from .forms import BasicInfoForm, ProjectForm, AddSkillForm
from .models import Skill
from online_portfolio.logger import logger
import os
from .helper import *
from helper import *
from django.contrib.auth.mixins import LoginRequiredMixin


class PortfolioEdit(LoginRequiredMixin, View):
    template = "portfolio/portfolio_edit.html"

    def get(self, request):
        basic_info = get_basic_info(request.user)
        projects = get_projects_info(request.user)

        are_skills_default, user_skill = get_skills(request.user.basicinfo)
        skills = json.dumps(user_skill)

        first_day = request.user.date_joined + datetime.timedelta(
            hours=3
        ) >= UTC.localize(datetime.datetime.now())

        context = basic_info
        context["projects"] = projects
        context["skills"] = skills
        context["are_skills_default"] = are_skills_default
        context["first_day"] = first_day
        return render(request, template_name=self.template, context=context)


class UpdateAboutSection(LoginRequiredMixin, View):
    """
    Updates the about section of the portfolio.
    """

    @staticmethod
    def post(request):
        basic_info = request.user.basicinfo

        name = (
            request.POST["name"].strip()
            if request.POST.get("name", "") != ""
            else basic_info.name
        )
        tagline = (
            request.POST["tag_line"].strip()
            if request.POST.get("tag_line", "") != ""
            else basic_info.tag_line
        )
        about = (
            request.POST["about"].strip()
            if request.POST.get("about", "") != ""
            else basic_info.about
        )
        picture = (
            request.POST["profile_pic"]
            if request.POST.get("profile_pic", "") != ""
            else basic_info.profile_pic
        )

        data = {
            "name": name,
            "about": about,
            "tag_line": tagline,
            "profile_pic": picture,
        }

        form = BasicInfoForm(data)

        # show error if data is invalid
        if not form.is_valid():
            error_dict = dict(form.errors.items())

            return JsonResponse(
                data=error_dict,
                status=HTTPStatus.UNPROCESSABLE_ENTITY,
                reason="Invalid Data",
            )

        basic_info.update(data)
        basic_info.save()

        return JsonResponse(
            data={}, status=HTTPStatus.OK, reason="Data Edited Successfully!"
        )


class EditProjects(LoginRequiredMixin, View):
    @staticmethod
    def post(request):
        project_id = int(request.POST["id"])
        project = Project.objects.get(pk=project_id)

        if project.user_profile != request.user.basicinfo:
            return JsonResponse({"success": False, "message": "error"})

        _get = request.POST.get

        data = {
            "title": _get("title", project.title),
            "description": _get("description", project.description),
            "skills": _get("skills", project.skills),
            "live_link": _get("liveLink", project.live_link),
            "code_link": _get("codeLink", project.code_link),
            "image": _get("image", project.image),
        }

        form = ProjectForm(data, instance=project)

        if not form.is_valid():
            return JsonResponse({"success": False, "message": "error"})

        form.save()
        return JsonResponse({"success": True, "message": "success"})


class DeleteProject(LoginRequiredMixin, View):
    @staticmethod
    def post(request):
        id_ = int(request.POST["id"])
        project = Project.objects.get(pk=id_)

        if project.user_profile != request.user.basicinfo:
            return JsonResponse({"success": False, "message": "error"})

        if request.user.basicinfo.total_projects == 1:
            return JsonResponse(
                {"succes": False, "message": "Cannot Delete All Projects"}
            )

        project.delete()

        basic_info = request.user.basicinfo
        basic_info.total_projects -= 1
        basic_info.save()

        return JsonResponse({"success": True, "message": "success"})


class AddNewProject(LoginRequiredMixin, View):
    @staticmethod
    def post(request):
        total_projects = request.user.basicinfo.total_projects

        if total_projects >= 10:
            return JsonResponse(
                {"success": False, "message": "You cannot have more than 10 projects"}
            )

        project = create_default_project(request.user)

        project_data = project.to_dict()
        return JsonResponse(
            {"success": True, "message": "success", "project_data": project_data}
        )


class ExportPortfolio(LoginRequiredMixin, View):
    template = "portfolio/portfolio_export.html"

    def post(self, request):
        basic_info = request.user.basicinfo
        about_data = {
            "name": basic_info.name,
            "profile_pic": basic_info.profile_pic,
            "tag_line": basic_info.tag_line,
            "about": as_markdown(basic_info.about),
        }

        projects = Project.objects.filter(user_profile=request.user.basicinfo)
        projects = [project.to_dict() for project in projects]

        for project in projects:
            project["description"] = as_markdown(project["description"])

        context = {
            "projects": projects,
            "username": request.user.username,
            "avoid_navbar": True,
            "copyright_link": request.scheme + "://" + request.get_host(),
            "copyright_value": request.get_host(),
        }
        context = {**context, **about_data}

        portfolio = render_to_string(self.template, context)

        with open(os.path.join(settings.BASE_DIR, "media", "port.html"), "wb") as file:
            file.write(portfolio.encode("utf-8"))

        with open(os.path.join(settings.BASE_DIR, "media", "port.html"), "rb") as file:
            fs = MediaStorage()
            file = fs.save(request.user.username + "portfolio.html", file)
            url = fs.url(file)
            basic_info.portfolio = url

        basic_info.save()
        os.remove(os.path.join(settings.BASE_DIR, "media", "port.html"))

        return JsonResponse({"success": True, "message": "success", "url": url})


class AddSkill(LoginRequiredMixin, View):
    @staticmethod
    def post(request):
        skill_name = request.POST.get("skill_name")
        category = request.POST.get("category")

        form = AddSkillForm(
            data={
                "user_profile": request.user.basicinfo,
                "skill_name": skill_name,
                "category": category,
            }
        )

        if not form.is_valid():
            error_dict = dict(form.errors.items())

            return JsonResponse(
                data=error_dict, status=HTTPStatus.BAD_REQUEST, reason="Invalid Data"
            )

        form.save()

        return JsonResponse(data={}, status=HTTPStatus.OK, reason="Success",)


class DeleteSkill(LoginRequiredMixin, View):
    @staticmethod
    def post(request):
        skill_name = request.POST.get("skillName")
        user_profile = request.user.basicinfo

        try:
            skill = Skill.objects.get(user_profile=user_profile, skill_name=skill_name)
        except ObjectDoesNotExist:
            return JsonResponse(
                data={},
                status=HTTPStatus.UNPROCESSABLE_ENTITY,
                reason="Skill Does Not Exists!!",
            )

        skill.delete()
        return JsonResponse(data={}, status=HTTPStatus.OK, reason="Success!!")


@require_POST
def change_category_name(request):
    old_name = request.POST["oldName"]
    new_name = request.POST["newName"]

    if len(new_name) > 50:
        return JsonResponse(
            data={},
            status=HTTPStatus.UNPROCESSABLE_ENTITY,
            reason="Category Names Should Have Upto 50 Characters!!",
        )

    skills = Skill.objects.filter(
        user_profile=request.user.basicinfo, category=old_name
    )

    for skill in skills:
        skill.category = new_name
        skill.save()

    return JsonResponse(data={}, status=HTTPStatus.OK, reason="Success!!")

online_portfolio/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>

    <link href="{% static 'generic/favicon.png' %}" rel="icon">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->

    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/portfolio_edit.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'portfolio/css/responsive.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Arimo:wght@700&family=Open+Sans:wght@400;800&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <!-- include summernote css/js -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">


    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.704.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</head>

<body>

    {% if not avoid_navbar %}
    {% include 'navbar.html' %}
    {% endif %}

    {% block content %}{% endblock %}

    {% include 'footer.html' %}

    <!-- include summernote css/js -->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="{% static 'portfolio/js/responsive.js' %}"></script>
</body>

{% block scripts %}{% endblock %}

</html>

online_portfolio/templates/portfolio/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#"><strong>Portfolio</strong></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">Edit Portfolio</a>
            </li>
            {% if portfolio %}
            <li class="nav-item">
                <a class="nav-link" id="portLink2" href="{{portfolio}}" target="_blank">View Portfolio</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="#">About Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Feedback</a>
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'accounts:logout' %}">
            <button class="btn btn-success my-2 my-sm-0" type="submit">Log Out</button>
        </form>
    </div>
</nav>

online_portfolio/templates/portfolio/portfolio_edit.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title %}
Edit | Portfolio
{% endblock %}

{% block content %}
<div class="modal" tabindex="-1" role="dialog" id="portfolioLink">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Share the following link!!</h5>

                <button type="button" class="close" onclick="closePortLink();" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <form>
                    <div class="form-group" style="text-align:left;">
                        <input type="text" class="form-control" id="portLink" value="">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="errorModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="background: #ff9999;">
            <div class="modal-header">
                <h5 class="modal-title"></h5>

                <button onclick="closeErrorModal();" type="button" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

{% if first_day %}
<div id="infoStrip">
    <p>Hi! this is a sample portfolio for your reference, it is completely editable so that you can make it yours. Just
        click on any field and you'll get it :).</p>
</div>
{% endif %}

<div id="titleDiv">
    <div id="titleWithButton">
        <div id="titleDivInner">
            <div>
                <img id="profile_pic_alt" class="img-fluid" {% if profile_pic %} src="{{profile_pic}}" {% else %}
                    src="{% static 'portfolio/avatar.png' %}" {% endif %} alt="Avatar">
                <input type="file" id="profile_picture" onchange="UploadProfilePic('{{request.user.username}}');">

                <h1 contenteditable="true" id="titleName" onfocusin="showCharCount('titleName', 'titleNameCharCount', 40);"
                    onfocusout="updateName();"><strong>{{name}}</strong></h1>
                <small id="titleNameCharCount" class="charCount"></small>
                <h5 contenteditable="true" id="titleTagline" onfocusin="showCharCount('titleTagline', 'titleTaglineCharCount', 55);"
                    onfocusout="updateTagline();">{{tag_line}}</h5>
                <small id="titleTaglineCharCount" class="charCount"></small>
            </div>
        </div>
    </div>
</div>

<div id="aboutDiv">
    <div id="aboutOrangeCharCount" class="charCount"></div>
    <div id="aboutOrange" onfocusin="aboutOrangeFocusIn(this, 500);" contenteditable="true">
        {{about}}
    </div>
</div>

<div id="skillsDiv">

    <div class="skillsGrey carousel slide" data-interval="false" id="carouselExampleControls" data-keyboard="false">

        <div id="skillContentDiv" class="carousel-inner">
        </div>

    </div>
</div>

<div class="section" id="projects_heading">
    <div id="project_heading_inner">
        <div id="project_heading_text">
            My Projects
        </div>

        <br>

        <div id="projectHeadingButton">
                <a href="#projectSection">
                        <div class="indicator">
                            <span class="projectArrow"></span>
                            <span class="projectArrow"></span>
                            <span class="projectArrow"></span>
                        </div>
                </a>
        </div>
    </div>
</div>

<div class="section" id="projectSection">

    <div id="projectTitleDiv">
        <div id="projectTitle">
            Portfolio Builder
        </div>
    </div>

    <div id="projectContentDiv">
        <div id="projectInfo">
            <div class="projectDesc">
                <ol>
                    <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</li>
                    <li>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown
                        printer took a galley of type and scrambled it to make a type specimen book.</li>
                    <li>It has survived not only five centuries, but also the leap into electronic typesetting,
                        remaining essentially unchanged.</li>
                    <li>It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
                        passages, and more recently with desktop publishing software like Aldus PageMaker including
                        versions of Lorem Ipsum.</li>
                </ol>
            </div>

            <div class="projectImage">
                <div class="projectImageInner">
                    <img class="img-fluid" src="{% static 'portfolio/project_sample_image.png' %}">
                </div>
            </div>
        </div>

        <div id="projectSkills">
            <div class="skillBar">
                <div class="skills">
                    <span><strong>Skills Utilized:</strong> Python, C++, Django</span>
                </div>

                    <div class="codeButtonsDiv">
                        <button class="btn">View Live</button>
                        <button class="btn">View Code</button>
                    </div>
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'portfolio/js/init-aws.js' %}"></script>
<script type="text/javascript" src="{% static 'portfolio/js/edit.js' %}"></script>
<script>
    const AddButtonPath = "{% static 'portfolio/plus.svg' %}";
    const DeleteButtonPath = "{% static 'portfolio/trash.png' %}";
    const CarouselButton = "{% static 'portfolio/icons8-chevron-left-96.png' %}";
    let json_skills = `{{skills|safe}}`;
    const skills = JSON.parse(json_skills.replace(/\n/g, " "));
    const edit_project_url = "{% url 'portfolio:edit_projects' %}";
    const export_url = "{% url 'portfolio:export_portfolio' %}";
    const update_about_url = "{% url 'portfolio:update_about' %}";
    const add_skill_url = "{% url 'portfolio:add_new_skill' %}";
    const delete_skill_url = "{% url 'portfolio:delete_skill' %}";
    let areSkillsDefault = "{{are_skills_default}}";
    const edit_category_name_url = "{% url 'portfolio:edit_category_name' %}";
</script>
{% endblock %}